# Generated by Django 3.2.5 on 2021-07-13 10:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=256)),
                ('emission', models.IntegerField()),
                ('tree_emission', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='CarbonEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_created', models.DateTimeField(auto_now_add=True)),
                ('quantity', models.FloatField(default=1)),
                ('details', models.TextField(max_length=256)),
                ('item_involved', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='CarbonEntry', to='carbon.item')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='CarbonEntry', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
