# Generated by Django 3.2.5 on 2021-07-14 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CarbonEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_created', models.DateTimeField(auto_now_add=True)),
                ('quantity', models.FloatField(default=1)),
                ('details', models.TextField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='CarbonItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=256)),
                ('emission', models.IntegerField()),
                ('tree_emission', models.IntegerField(default=0)),
                ('unit', models.TextField(max_length=256, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='GreenEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_created', models.DateTimeField(auto_now_add=True)),
                ('quantity', models.FloatField(default=1)),
                ('details', models.TextField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='GreenItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=256)),
                ('oxygen', models.IntegerField()),
                ('tree_oxygen', models.IntegerField(default=0)),
                ('unit', models.TextField(max_length=256, null=True)),
            ],
        ),
    ]
