# Generated by Django 3.2.5 on 2021-07-14 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carbon', '0003_item_unit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='emission',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
    ]
