# Generated by Django 3.2.5 on 2021-07-14 18:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('carbon', '0004_alter_item_emission'),
    ]

    operations = [
        migrations.CreateModel(
            name='GreenItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=256)),
                ('oxygen', models.IntegerField()),
                ('tree_oxygen', models.IntegerField(default=0)),
                ('unit', models.TextField(max_length=256, null=True)),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='GreenEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_created', models.DateTimeField(auto_now_add=True)),
                ('quantity', models.FloatField(default=1)),
                ('details', models.TextField(max_length=256)),
                ('item_involved', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='GreenEntry', to='carbon.greenitem')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='GreenEntry', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CarbonItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=256)),
                ('emission', models.IntegerField()),
                ('tree_emission', models.IntegerField(default=0)),
                ('unit', models.TextField(max_length=256, null=True)),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='carbonentry',
            name='item_involved',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='CarbonEntry', to='carbon.carbonitem'),
        ),
        migrations.DeleteModel(
            name='Item',
        ),
    ]
