# Generated by Django 3.2.5 on 2021-07-14 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Donation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.TextField(max_length=256)),
                ('quantity', models.IntegerField()),
                ('credit_card_number', models.TextField(max_length=16)),
                ('expiration_year', models.TextField()),
                ('expiration_month', models.IntegerField()),
                ('confirm_code', models.TextField(max_length=3)),
                ('time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
