# Generated by Django 3.2.5 on 2021-07-14 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donation', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='donation',
            old_name='username',
            new_name='firstname',
        ),
        migrations.AddField(
            model_name='donation',
            name='lastname',
            field=models.TextField(max_length=256, null=True),
        ),
    ]
