# Generated by Django 3.2.5 on 2021-07-14 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='default_emissions',
            field=models.IntegerField(default=50),
        ),
        migrations.AddField(
            model_name='user',
            name='type_of_lifestyle',
            field=models.CharField(choices=[('ACT', 'Active'), ('ITD', 'Indoors'), ('SOC', 'Social'), ('INT', 'High Brain-Usage'), ('RET', 'Retired'), ('VAC', 'Very Active')], default='ACT', max_length=3),
        ),
    ]
